2/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Mail;
use App\Mail\Contactanos;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('blogUser', \App\Http\Controllers\BlogUserController::class);

Route::get('/', function () {
    $app = app();
    $controller = $app->make('\App\Http\Controllers\BlogUserController');
    return $controller->callAction('index', $parameters = array());
})->name('welcome');


Route::resource('contacts', \App\Http\Controllers\ContactController::class);
Route::resource('adminContacts', \App\Http\Controllers\AdminContactController::class);
Route::resource('adminBlog', \App\Http\Controllers\BlogController::class);
Route::get('contactanos',function(){
    $correo = new Contactanos;
    Mail::to('dcasaverdec@ulasalle.edu.pe')->send($correo);
    return "Comentario enviado, usted recibira un correo de confrimación";
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('tasks', \App\Http\Controllers\TasksController::class);

    Route::resource('users', \App\Http\Controllers\UsersController::class);
    Route::resource('members', \App\Http\Controllers\MembersController::class);
});

2/app/Models/Member.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    use HasFactory;
    protected $fillable = ['user_name', 'first_name', 'last_name', 'mobile', 'email', 'dob', 'address', 'fees'];
}

2/app/Http/Controllers/MembersController.php
<?php

namespace App\Http\Controllers;

use App\Models\Member;
use Illuminate\Http\Request;


class MembersController extends Controller
{
    public function index(){
        $members = Member::latest()->paginate(2);
        return view('members.index', compact('members'));
    }
    public function create(){
        return view('members.create');
    }

    public function store(Request $request){
        $request->validate([
            'user_name'=> 'required',
            'first_name'=>'required',
            'email'=>'required',
            'fees'=>'required',
        ]);
        Member::create($request->all());

        return redirect()->route('members.index')->with('success', 'profile created succesfully!!');
    }

    public function show(Member $member){
        return view('members.show', compact('member'));
    }



    public function edit(Member $member){
        return view('members.edit', compact('member'));
    }

    public function update(Request $request, $id){
        $request->validate([
            'user_name'=> 'required',
            'first_name'=>'required',
            'email'=>'required',
        ]);
        $members = $request -> all();
        Member::find($id) -> update($members);

        return redirect()->route('members.index')->with('success', 'profile Updated succesfully!!');


    }
    public function destroy($members){
        Member::destroy($members);
        return redirect()->route('members.index')->with('success', 'profile Deleted succesfully!!');
    }
}

2/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

2/resources/views/members/create.blade.php
@extends('members.layout')
@section('content')
<x-app-layout>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Create Members 
        </h2>
    </x-slot>

<div class="container mt-5">
    <form action="{{route('members.store')}}" method="POST">
        @csrf



        <div class="row">
            <div class="col-6">
                <label>User name</label>
                <input type="text" name="user_name" class="form-control" placeholder="ayan123">
                <br>
            </div>
            <div class="col-6">
                <label>Date Of Birth</label>
                <input type="date" name="dob" class="form-control">
                <br>
            </div>
        </div>


        <div class="row">
            <div class="col-6">
                <label>First Name</label>
                <input type="text" name="first_name" class="form-control" placeholder="First name">
                <br>
            </div>
            <div class="col-6">
                <label>Last Name</label>
                <input type="text" name="last_name" class="form-control" placeholder="Last name">
                <br>
            </div>
        </div>
        <label>Email</label>
        <input type="text" name="email" class="form-control" placeholder="gym@gmail.com">
        <br>
        <div class="row">
            <div class="col-6">
                <label>Mobile</label>
                <input type="text" name="mobile" class="form-control" placeholder="017*****">
                <br>
            </div>
            <div class="col-6">
                <label>Address</label>
                <input type="text" name="address" class="form-control" placeholder="address">
                <br>
            </div>
        </div>
        <label>Fees</label>
                <input type="text" name="fees" class="form-control" placeholder="1440.00">
        <br>



        <button class="btn btn-info" type="submit">ADD</button>

    </form>
</div>
</x-app-layout>

2/resources/views/members/edit.blade.php
@extends('members.layout')
@section('content')

<x-app-layout>
@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Edit Members
        </h2>
    </x-slot>


<div class="container mt-5">
    
    <form action="{{route('members.update', $member->id)}}" method="POST">
        @csrf
        @method('PUT')

       


        <div class="row">
            <div class="col-6">
                <label>User Name</label>
                <input type="text" name="user_name" class="form-control" placeholder="ayan123" value="{{$member->user_name}}">
                <br>
            </div>
            <div class="col-6">
                <label>Date Of Birth</label>
                <input type="text" name="dob" class="form-control" placeholder="20-20-2002" value="{{$member->dob}}">
                <br>
            </div>
        </div>

        <div class="row">
            <div class="col-6">
                <label>First Name</label>
                <input type="text" name="first_name" class="form-control" placeholder="First Name" value="{{$member->first_name}}">
                <br>
            </div>
            <div class="col-6">
                <label>Last Name</label>
                <input type="text" name="last_name" class="form-control" placeholder="Last Name" value="{{$member->last_name}}">
                <br>
            </div>
        </div>
        <label>Email</label>
        <input type="text" name="email" class="form-control" placeholder="aaziz9642@gmail.com" value="{{$member->email}}">
        <br>

        <div class="row">
            <div class="col-6">
            <label>Mobile</label>
        <input type="text" name="mobile" class="form-control" placeholder="017******" value="{{$member->mobile}}">
        <br>
            </div>
            <div class="col-6">
            <label>Address</label>
        <input type="text" name="address" class="form-control" placeholder="017******" value="{{$member->address}}">
        <br>
            </div>
        </div>

        <label>Fees</label>
        <input type="text" name="fees" class="form-control" placeholder="017******" value="{{$member->fees}}">
        <br>
        
        <button class="btn btn-info" type="submit">Update</button>

    </form>
</div>
</x-app-layout>

2/resources/views/members/index.blade.php
@extends('members.layout')
@section('content')
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            ALL Members
        </h2>
    </x-slot>

 

@if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    

<div class="container">
    <a class="btn btn-info mt-5 mb-2" href="{{route('members.create')}}">Add a Member</a>
    <div>
    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">
    </div>
    
    <table class="table table-striped" id="myTable">
        <thead>
            <tr>
                <th scope="col">User name</th>
                <th scope="col">First Name</th>
                <th scope="col">Email</th>
                <th scope="col">Address</th>
                <th scope="col">Fees</th>
                <th scope="col">Action</th>


            </tr>
        </thead>
        @foreach ($members as $member)
        

            <tr>
                <td>{{$member->user_name}}</td>
                <td>{{$member->first_name}}</td>
                <td>{{$member->email}}</td>
                <td>{{$member->address}}</td>
                <td>{{$member->fees}}</td>
                <td>
                    <form action="{{route('members.destroy', $member->id)}}" method="POST" onsubmit="return confirm('Are you sure?');">
                        <a class="btn btn-primary" href="{{route('members.show', $member->id)}}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                        <a class="btn btn-warning m-2" href="{{route('members.edit', $member->id)}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit"><i class="fa fa-trash" aria-hidden="true"></i></button>
                    </form>
                </td>
            </tr>
        
        @endforeach
    </table>
    {{$members->links()}}
      </span>
      <style>
      .w-5{
        display: none;
      }
      </style>

</div>

</x-app-layout>

2/resources/views/members/layout.blade.php
<html>

<head>
    <title>
        gym.com
    </title>
    <meta charset="utf-8">
    <style>
* {
  box-sizing: border-box;
}

#myInput {
  background-image: url('/css/searchicon.png');
  background-position: 10px 10px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}

#myTable {
  border-collapse: collapse;
  width: 100%;
  border: 1px solid #ddd;
  font-size: 18px;
}

#myTable th, #myTable td {
  text-align: left;
  padding: 12px;
}

#myTable tr {
  border-bottom: 1px solid #ddd;
}

#myTable tr.header, #myTable tr:hover {
  background-color: #f1f1f1;
}
</style>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
</head>

<body>
    

    <div class="container">
    
    @yield('content')
   
    </div>
</body>
<script>
function myFunction() {
  // Declare variables
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

</html>

2/resources/views/members/show.blade.php
@extends('members.layout')
@section('content')
<x-app-layout>
<x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        Show user
        </h2>
    </x-slot>


<div class="container mt-5">
   
    <form action="{{route('members.update', $member->id)}}" method="POST">
        @csrf
        @method('PUT')
        <div class="row">
            <div class="col-6">
                <label>User Name</label>
                <input type="text" name="user_name" class="form-control" placeholder="ayan123" value="{{$member->user_name}}" readonly>
                <br>
            </div>
            <div class="col-6">
                <label>Date Of Birth</label>
                <input type="text" name="user_name" class="form-control" placeholder="ayan123" value="{{$member->dob}}" readonly>
                <br>
            </div>
        </div>

        <div class="row">
            <div class="col-6">
                <label>First Name</label>
                <input type="text" name="first_name" class="form-control" placeholder="ayan123" value="{{$member->first_name}}" readonly>
                <br>
            </div>
            <div class="col-6">
                <label>Last Name</label>
                <input type="text" name="last_name" class="form-control" placeholder="ayan123" value="{{$member->last_name}}" readonly>
                <br>
            </div>
        </div>
        <label>Email</label>
        <input type="text" name="email" class="form-control" placeholder="ayan123" value="{{$member->email}}" readonly>
        <br>

        <div class="row">
            <div class="col-6">
                <label>Mobile</label>
                <input type="text" name="mobile" class="form-control" placeholder="ayan123" value="{{$member->mobile}}" readonly>
                <br>
            </div>
            <div class="col-6">
                <label>Address</label>
                <input type="text" name="mobile" class="form-control" placeholder="ayan123" value="{{$member->address}}" readonly>
                <br>
            </div>
        </div>

        <label>Fees</label>
        <input type="text" name="mobile" class="form-control" placeholder="ayan123" value="{{$member->fees}}" readonly>
        <br>


    </form>

</div>
</x-app-layout>