2/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Mail;
use App\Mail\Contactanos;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('blogUser', \App\Http\Controllers\BlogUserController::class);

Route::get('/', function () {
    $app = app();
    $controller = $app->make('\App\Http\Controllers\BlogUserController');
    return $controller->callAction('index', $parameters = array());
})->name('welcome');


Route::resource('contacts', \App\Http\Controllers\ContactController::class);
Route::resource('adminContacts', \App\Http\Controllers\AdminContactController::class);
Route::resource('adminBlog', \App\Http\Controllers\BlogController::class);
Route::get('contactanos',function(){
    $correo = new Contactanos;
    Mail::to('dcasaverdec@ulasalle.edu.pe')->send($correo);
    return "Comentario enviado, usted recibira un correo de confrimación";
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('tasks', \App\Http\Controllers\TasksController::class);

    Route::resource('users', \App\Http\Controllers\UsersController::class);
    Route::resource('members', \App\Http\Controllers\MembersController::class);
});

2/app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;
    protected $fillable = ["title", "author", "descriptions", "img_path"];
}

2/app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::latest()->paginate(5);
        return view('blogs.index', compact('blogs'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('blogs.create');    
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'title'=> 'required',
            'descriptions'=>'required',
            'author'=>'required',
            'img_path' => 'required|image|max:5048',

        ]);
        $imageName = time().'.'.$request->img_path->extension();  
        $request->img_path->move(public_path('upload'), $imageName);
        $data = new Blog();
        $data->title = $request->title;
        $data->descriptions = $request->descriptions;
        $data->author = $request->author;
        $data->img_path = $imageName;
        $data->save();


        return redirect()->route('adminBlog.index')->with('success', 'Blog created succesfully!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('blogs.show', [
            'blogs' => Blog::findOrFail($id)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('blogs.edit', [
            'blogs' => Blog::findOrFail($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $data)
    {
        $request->validate([
            'title'=> 'required',
            'descriptions'=>'required',
            'author'=>'required',
            'img_path' => 'required|image|max:5048',

        ]);
        $imageName = time().'.'.$request->img_path->extension();  
        $request->img_path->move(public_path('upload'), $imageName);
        $data = new Blog();
        $data->title = $request->title;
        $data->descriptions = $request->descriptions;
        $data->author = $request->author;
        $data->img_path = $imageName;
        $data->update();
       

        return redirect()->route('adminBlog.index')->with('success', 'Blog created succesfully!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Blog::destroy($id);
        return redirect()->route('adminBlog.index')->with('success', 'profile Deleted succesfully!!');
    }
}

2/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

2/resources/views/blogs/create.blade.php
@extends('members.layout')
@section('content')
<x-app-layout>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Create Blog
        </h2>
    </x-slot>

<div class="container mt-5">
    <form action="{{route('adminBlog.store')}}" method="POST" enctype="multipart/form-data">
        @csrf



        <div class="row">
            <div class="col-6">
                <label>Title</label>
                <input type="text" name="title" class="form-control" placeholder="title">
                <br>
            </div>
            <div class="col-6">
                <label>Descriptions</label>
                <textarea type="text" name="descriptions" class="form-control" placeholder="descriptions"></textarea>
                <br>
            </div>
        </div>


        <div class="row">
            <div class="col-6">
                <label>Author</label>
                <input type="text" name="author" class="form-control" placeholder="author">
                <br>
            </div>
            <div class="col-6">
                <label>Image</label>
                <input type="file" name="img_path" class="form-control">
                <br>
            </div>
        </div>
        <button class="btn btn-info" type="submit">ADD</button>

    </form>
</div>
</x-app-layout>

2/resources/views/blogs/edit.blade.php
@extends('members.layout')
@section('content')

<x-app-layout>
@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Edit Members
        </h2>
    </x-slot>


<div class="container mt-5">
    
<form action="{{route('adminBlog.update', $blogs->id)}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-6">
                <label>Title</label>
                <input type="text" name="title" class="form-control" placeholder="title" value="{{$blogs->title}}">
                <br>
            </div>
            <div class="col-6">
                <label>Descriptions</label>
                <textarea type="text" name="descriptions" class="form-control" placeholder="descriptions">{{$blogs->descriptions}}</textarea>
                <br>
            </div>
        </div>


        <div class="row">
            <div class="col-6">
                <label>Author</label>
                <input type="text" name="author" class="form-control" placeholder="author" value="{{$blogs->author}}">
                <br>
            </div>
            <div class="col-6">
            <label>Old Image</label>
            <div><img src="/upload/{{$blogs->img_path}}" style="max-height:100px" ;></div>
                <label>Add new Image</label>
                <input type="file" name="img_path" class="form-control" >
                <br>
            </div>
        </div>

       


        
        
        <button class="btn btn-info" type="submit">Update</button>

    </form>
</div>
</x-app-layout>

2/resources/views/blogs/index.blade.php
@extends('members.layout')
@section('content')
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            ALL Members
        </h2>
    </x-slot>



    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif



    <div class="container">
        <a class="btn btn-info mt-5 mb-2" href="{{route('adminBlog.create')}}">Add a Blog</a>
        <div>
            <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">
        </div>

        <table class="table table-striped" id="myTable">
            <thead>
                <tr>
                    <th scope="col">Photo</th>
                    <th scope="col">Title</th>
                    <th scope="col">Descriptions</th>
                    <th scope="col">Author</th>
                    <th scope="col">Action</th>


                </tr>
            </thead>
            @foreach ($blogs as $blog)


            <tr>
            <td><img src="/upload/{{$blog->img_path}}" style="max-height:50px";></td>
                <td>{{substr($blog->title,0 , 30)}}...</td>
                <td>{{substr($blog->descriptions,0 , 30)}}...</td>
                <td>{{substr($blog->author,0 , 20)}}...</td>
                <td>
                    <form action="{{route('adminBlog.destroy', $blog->id)}}" method="POST">
                        <a class="btn btn-primary" href="{{route('adminBlog.show', $blog->id)}}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                        <a class="btn btn-warning m-2" href="{{route('adminBlog.edit', $blog->id)}}"><i class="fa fa-pencil-square-o" aria-hidden="true" ></i></a>
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit"><i class="fa fa-trash" aria-hidden="true"></i></button>
                    </form>
                </td>
            </tr>

            @endforeach
            
        </table>
        {{$blogs->links()}}
      </span>
      <style>
      .w-5{
        display: none;
      }
      </style>

    </div>

</x-app-layout>

2/resources/views/blogs/layout.blade.php
<html>

<head>
    <title>
        gym.com
    </title>
    <meta charset="utf-8">
    <style>
* {
  box-sizing: border-box;
}

#myInput {
  background-image: url('/css/searchicon.png');
  background-position: 10px 10px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}

#myTable {
  border-collapse: collapse;
  width: 100%;
  border: 1px solid #ddd;
  font-size: 18px;
}

#myTable th, #myTable td {
  text-align: left;
  padding: 12px;
}

#myTable tr {
  border-bottom: 1px solid #ddd;
}

#myTable tr.header, #myTable tr:hover {
  background-color: #f1f1f1;
}
</style>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
</head>

<body>
    

    <div class="container">
    
    @yield('content')
   
    </div>
</body>
<script>
function myFunction() {
  // Declare variables
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

</html>

2/resources/views/blogs/show.blade.php
@extends('members.layout')
@section('content')

<x-app-layout>
@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Edit Members
        </h2>
    </x-slot>


<div class="container mt-5">
    
<form>
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-6">
                <label>Title</label>
                <input type="text" name="title" class="form-control" placeholder="title" value="{{$blogs->title}}" readonly>
                <br>
            </div>
            <div class="col-6">
                <label>Descriptions</label>
                <textarea type="text" name="descriptions" class="form-control" placeholder="descriptions" readonly>{{$blogs->descriptions}}</textarea>
                <br>
            </div>
        </div>


        <div class="row">
            <div class="col-6">
                <label>Author</label>
                <input type="text" name="author" class="form-control" placeholder="author" value="{{$blogs->author}}" readonly>
                <br>
            </div>
            <div class="col-6">
            <label>Image</label>
            <div><img src="/upload/{{$blogs->img_path}}" style="max-height:100px" ;></div>

                <br>
            </div>
        </div>

       

    </form>
</div>
</x-app-layout>